// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrTGUASn0hqhyd2Wr3D4fPacYJgBWjvTM',
    appId: '1:558675229569:web:d597bfd980a30f304e8680',
    messagingSenderId: '558675229569',
    projectId: 'hibalo',
    authDomain: 'hibalo.firebaseapp.com',
    storageBucket: 'hibalo.firebasestorage.app',
    measurementId: 'G-EXLBSW4V58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcdcCw3SrjnHYHPDJouo6CGNVATpgbkpg',
    appId: '1:558675229569:android:371129da51c72e344e8680',
    messagingSenderId: '558675229569',
    projectId: 'hibalo',
    storageBucket: 'hibalo.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWHcYyyNPgE5W1GUxIawtMNxOgaGu6J-o',
    appId: '1:558675229569:ios:4025ac1d548f056b4e8680',
    messagingSenderId: '558675229569',
    projectId: 'hibalo',
    storageBucket: 'hibalo.firebasestorage.app',
    iosBundleId: 'com.example.hibaloApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWHcYyyNPgE5W1GUxIawtMNxOgaGu6J-o',
    appId: '1:558675229569:ios:4025ac1d548f056b4e8680',
    messagingSenderId: '558675229569',
    projectId: 'hibalo',
    storageBucket: 'hibalo.firebasestorage.app',
    iosBundleId: 'com.example.hibaloApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrTGUASn0hqhyd2Wr3D4fPacYJgBWjvTM',
    appId: '1:558675229569:web:0c5ce2be6b5769df4e8680',
    messagingSenderId: '558675229569',
    projectId: 'hibalo',
    authDomain: 'hibalo.firebaseapp.com',
    storageBucket: 'hibalo.firebasestorage.app',
    measurementId: 'G-HE95177MNJ',
  );
}
