// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU4H6xlyK37vzXNRBPJJ80ZIB2H1U_7Qg',
    appId: '1:134997593443:web:ca6eb1003ffa9729419756',
    messagingSenderId: '134997593443',
    projectId: 'hibalo-c1967',
    authDomain: 'hibalo-c1967.firebaseapp.com',
    storageBucket: 'hibalo-c1967.firebasestorage.app',
    measurementId: 'G-KZMQ89668P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMsMVK0Lww7GkdjP6MS_ljE25Wjp2dbvs',
    appId: '1:134997593443:android:95ce7548186a1598419756',
    messagingSenderId: '134997593443',
    projectId: 'hibalo-c1967',
    storageBucket: 'hibalo-c1967.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxd69VHGI5cJBGn1z_MJnIm2Svd5Znnzk',
    appId: '1:134997593443:ios:42487bdf41d4cfcc419756',
    messagingSenderId: '134997593443',
    projectId: 'hibalo-c1967',
    storageBucket: 'hibalo-c1967.firebasestorage.app',
    iosBundleId: 'com.example.hibaloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxd69VHGI5cJBGn1z_MJnIm2Svd5Znnzk',
    appId: '1:134997593443:ios:42487bdf41d4cfcc419756',
    messagingSenderId: '134997593443',
    projectId: 'hibalo-c1967',
    storageBucket: 'hibalo-c1967.firebasestorage.app',
    iosBundleId: 'com.example.hibaloApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU4H6xlyK37vzXNRBPJJ80ZIB2H1U_7Qg',
    appId: '1:134997593443:web:022910747582c331419756',
    messagingSenderId: '134997593443',
    projectId: 'hibalo-c1967',
    authDomain: 'hibalo-c1967.firebaseapp.com',
    storageBucket: 'hibalo-c1967.firebasestorage.app',
    measurementId: 'G-53VPB54JVZ',
  );
}
